### ISSUE TITLE
Allow arbitrary blockchain

### ISSUE THREAD

**Issue by jasny** [chainpoint/chainpoint-proof-json-schema#1]
Chainpoint is supposed to be an open standard. However only allowing anchoring to Calendar, Ethereum or Bitcoin makes it very restrictive.

Please remove the `enum` and allow anchoring to any blockchain.

https://github.com/chainpoint/chainpoint-proof-json-schema/blob/master/index.js#L54

        'type': {
          'description': 'A trust anchor',
          'title': 'One of the known trust anchor types. Calendar (cal), Ethereum (eth), and Bitcoin (btc).',
          'type': 'string',
          'enum': ['cal', 'eth', 'btc']
        }

**Comment by grempe** [comment]
Hi @jasny,

I'm curious to learn more about the goal you are trying to achieve with this suggested change. I've reached out to you directly via email as well.

Cheers

**Comment by phptek** [comment]
For the rest of us, what was the upshot of the discussion? For now, I see where @jasny is coming from.

**Comment by jasny** [comment]
We've been anchoring on the [Waves platform](https://wavesplatform.com/). We've recently set up our own public blockchain [LTO Network](http://lto.network) designed specifically for anchoring.

There are many blockchains which can be used for anchoring. Others may want to anchor to Neo or NEM. Restricting it to `cal`, `eth` and `btc` makes this standard not very open to other implementations.

**Comment by phptek** [comment]
@jasny thanks for adding the detail.

**Comment by grempe** [comment]
I've addressed this issue in commit:

https://github.com/chainpoint/chainpoint-proof-json-schema/commit/5e0c95a8a18a2f96f5390234a7e53a29606e7500

A new version `1.0.2` of the validator has been pushed to npm:
https://www.npmjs.com/package/chainpoint-proof-json-schema

You can now validate using any arbitrary anchor type name, but it must be lowercase `a-z` between 3 and 10 characters in length. This replaces the Enum of `['cal', 'eth', 'btc']`

We'd be interested in any proofs being generated with this proof format remaining compatible with our other Chainpoint proof validation tools. Please report to us any issues with that validation so that we can make changes, or guide you in changes you should make to remain compliant.

See beta demo of the Chainpoint Web Client: https://chainpoint.org/demo/

Cheers
